WITH obt AS (
    SELECT
        BOOKING_ID,
        LISTING_ID,
        HOST_ID,
        TOTAL_AMOUNT,
        ACCOMMODATES,
        BEDROOMS,
        BATHROOMS,
        PRICE_PER_NIGHT,
        RESPONSE_RATE,
        CREATED_AT
    FROM {{ ref('obt') }}
)

SELECT
    OBT.BOOKING_ID,
    OBT.LISTING_ID,
    OBT.HOST_ID,
    OBT.TOTAL_AMOUNT,
    OBT.ACCOMMODATES,
    OBT.BEDROOMS,
    OBT.BATHROOMS,
    OBT.PRICE_PER_NIGHT,
    OBT.RESPONSE_RATE
FROM obt AS OBT
LEFT JOIN {{ ref('dim_listings') }} AS DIM_LISTINGS
    ON OBT.LISTING_ID = DIM_LISTINGS.LISTING_ID
    AND OBT.CREATED_AT >= DIM_LISTINGS.DBT_VALID_FROM
    AND OBT.CREATED_AT < COALESCE(DIM_LISTINGS.DBT_VALID_TO, TO_TIMESTAMP_NTZ('9999-12-31'))
LEFT JOIN {{ ref('dim_hosts') }} AS DIM_HOSTS
    ON OBT.HOST_ID = DIM_HOSTS.HOST_ID
    AND OBT.CREATED_AT >= DIM_HOSTS.DBT_VALID_FROM
    AND OBT.CREATED_AT < COALESCE(DIM_HOSTS.DBT_VALID_TO, TO_TIMESTAMP_NTZ('9999-12-31'))
